name: job-matcher-app
services:
- name: backend
  dockerfile_path: Dockerfile.backend
  source_dir: .
  http_port: 8000
  instance_count: 1
  instance_size_slug: professional-xs
  envs:
  - key: GEMINI_API_KEY
    scope: RUN_AND_BUILD_TIME
    value: "PLACEHOLDER_ENTER_IN_DASHBOARD"

- name: frontend
  dockerfile_path: Dockerfile.frontend
  source_dir: .
  http_port: 80
  instance_count: 1
  instance_size_slug: professional-xs
  routes:
  - path: /
